alert("Привет мир");
let money = 30;
let income ='Доход';
let addExpenses = 23;
const deposit = 56;
let mission = 176;
const period = prompt('Что-то написать');
console.log('money: ', money);
console.log('income:', income);
console.log('period', period);